/**
 * Генерация src/data/book_data.js из HTML-книги (тот же пайплайн, что в приложении).
 * Использование:
 *   node tools/parse_book.mjs [путь-к-html] [путь-к-выходу]
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { parseHtmlBook } from '../src/utils/parser.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const defaultHtml = path.resolve(__dirname, '../../Martin-Kleppmann---Designing-Data-Intensive-Applications.html');
const defaultOut = path.resolve(__dirname, '../src/data/book_data.js');

const htmlPath = process.argv[2] ? path.resolve(process.argv[2]) : defaultHtml;
const outPath = process.argv[3] ? path.resolve(process.argv[3]) : defaultOut;

const html = fs.readFileSync(htmlPath, 'utf8');
const book = parseHtmlBook(html, path.basename(htmlPath));

const payload = {
  title: book.title,
  author: 'Martin Kleppmann',
  chapters: book.chapters,
};

const header = `// Auto-generated by tools/parse_book.mjs — DO NOT EDIT\n// Source: ${path.basename(htmlPath)}\n`;
const body = `export const BOOK_DATA = ${JSON.stringify(payload, null, 2)};\n`;

fs.writeFileSync(outPath, header + body, 'utf8');
console.log('Written', outPath, '| chapters:', book.chapters.length);
console.log('Примечание: book_data.js в .gitignore — для legacy HTML-импорта используйте файл через библиотеку.');
